source: docs
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
theme: hacker
baseurl: /Isakgraarud.github.io
url: https://Isakgraarud.com
destination: ./_site